name: CI

env:
  GRADLE_OPTS: '-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false'

on:
  pull_request:
    paths-ignore: [ '**/**.md' ]

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci-build:
    runs-on: macos-latest
    
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'skip-ci') }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          validate-wrappers: true
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
          gradle-home-cache-cleanup: true

      - name: Run build (includes testing and spotless check)
        run: ./gradlew build --stacktrace

      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-reports
          retention-days: 7
          path: |
            **/build/reports/*

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          retention-days: 7
          path: |
            **/build/test-results/*
